services:
  granitedb:
    image: postgres:latest
    container_name: granitedb
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - granitedb:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  granite:
    container_name: granite
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - granitedb
    volumes:
      - ./:/app

volumes:
  granitedb:
    driver: local

