[build]
bin = "bin/granite" 
cmd = "go build -o bin/granite ./cmd/granite-identity" 
include_ext = ["go", "tpl", "tmpl", "html"] 
exclude_dir = ["vendor", "tmp"] 
exclude_file = ["air.toml"] 

[log]
level = "debug"
