apiVersion: apps/v1
kind: Deployment
metadata:
  name: granite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: granite
  template:
    metadata:
      labels:
        app: granite
    spec:
      containers:
      - name: granite
        image: caiogallo2401/granite-identity:latest
        ports:
        - containerPort: 8080
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: granite
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: granite

