// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Balance       pgtype.Numeric
	Currency      string
	Status        string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	AccountType   string
	AccountNumber string
	LastActivity  pgtype.Timestamp
}

type Transaction struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Type        string
	Amount      pgtype.Numeric
	Currency    string
	CreatedAt   pgtype.Timestamp
	ReferenceID string
	Description pgtype.Text
}
